linters:
  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false

  Comment:
    enabled: false

  LeadingZero:
    enabled: false

  NameFormat:
    convention: '^[a-z][-a-zA-Z0-9_]*$'

  MergeableSelector:
    force_nesting: false

  PlaceholderInExtend:
    enabled: false

  PropertySortOrder:
    enabled: false

  PseudoElement:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    convention: '^[a-z][-a-zA-Z0-9_]*$'

  Shorthand:
    enabled: true

  StringQuotes:
    style: double_quotes

  TrailingZero:
    enabled: true

  UrlQuotes:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false

  QualifyingElement:
    enabled: false
